### ISSUE TITLE
Невозможно редактировать профиль

### ISSUE THREAD

**Issue by pepebotika69** [cusodede/bc#15]
урл: /users/profile

Не найден контроллер

![Screenshot from 2021-05-25 15-26-01](https://user-images.githubusercontent.com/14938095/119497780-9e4f1580-bd6d-11eb-96de-bd7c75945924.png)

**Comment by pozitronik** [comment]
Потому что @alxlapin сделал по-своему.
Пример того, как стоит делать редактирование единичных атрибутов: \app\controllers\PermissionsController::actions

Для пользюков впилю сам.

**Comment by pozitronik** [comment]
upd: к @alxlapin вопрос снимается, редактирование в примере сделано для EditableColumnAction. Для инлайн-редактора требуется немного другое решение.

**Comment by pozitronik** [comment]
Решено:

b7339d7ebee3773d064a1dc2af1ce5e756882ca6
8702ed4d7d68acc3204a15fac82a56990553d254
5ff55a8be009f1bc78b1c958c8a92804d0c88836
81d0945fbd29d16f84baf01726322bfe3a427917
