### ISSUE TITLE
ActiveRecordTrait: refresh model after save

### ISSUE THREAD

**Issue by alxlapin** [cusodede/bc#24]
https://github.com/cusodede/bc/blob/cadf64308108c34803477be2587c564bd307047a/models/core/prototypes/ActiveRecordTrait.php#L96

https://github.com/cusodede/bc/blob/cadf64308108c34803477be2587c564bd307047a/models/core/prototypes/ActiveRecordTrait.php#L111

Вероятно, можно обойтись и без refresh(). 
Но надо учитывать кейсы с триггерами, преднастроенными на уровне БД (CURRENT_TIMESTAMP, к примеру). 
В таком случае, надо помнить о behaviors.

**Comment by pozitronik** [comment]
Эта история уходит корнями в глубокое прошлое, когда я, запершись в одной из переговорок, херачил в одно рыло очередной гигасервис, которому, конечно, нужен был свой движок. Некоторые идеи из этого движка прижились, некоторые отмерли, а некоторые как бы есть, но не очень доведены до ума.
Это:
https://github.com/cusodede/bc/blob/cadf64308108c34803477be2587c564bd307047a/models/core/prototypes/ActiveRecordTrait.php#L92
одна из "недоведённых". Свою задачу она делает, но могло быть лучше.

Что за задача?
У нас есть [трейт релейшенов](https://github.com/pozitronik/yii2-core-tools/blob/master/src/traits/Relations.php), и он, в целом, работает прекрасно. Этот трейт надо вешать на доску почёта, давать ему премию и снимать про него кино, потому что весь головняк связей "многие ко многим" он убирает легко и просто. Если нам нужно сделать одну ActiveRecord-модель атрибутом другой, то что-то вроде
```php
/**
 * @return ActiveQuery
 */
public function getSellers():ActiveQuery {
	return $this->hasMany(Sellers::class, ['id' => 'seller_id'])->via('relatedStoresToSellers');
}

/**
 * @param mixed $sellers
 * @throws Throwable
 */
public function setSellers($sellers):void {
	RelStoresToSellers::linkModels($this, $sellers);
}
```

позволяет это сделать. Мы теперь можем просто присваивать атрибут сущности, не беспокоясь о прописывании связующего кода. ```$this->selers = Sellers::findOne(100500)```, всё. Или во вьюхе, например:
```php
<?= $form->field($model, 'sellers')->widget(Select2::class, [
	'data' => Sellers::find()->all()/*вот это ни фига себе, это будет работать!*/
]) ?>
```
В общем, решены все проблемы.
Кроме одной.

Что делать, если мы собираемся слинковать две сущности при создании первой? Т.е. $this существует, атрибут существует, а запись в БД не существует? Атрибуты ведь присваиваются до save()?

Вот эту задачу я и попытался решить в createModel(). Функция сначала сохраняет обычные, не relational-атрибуты (создавая на этом этапе запись в БД), затем смотрит, какие атрибуты не сохранились, предполагает, что это были релейшены, и сохраняет уже и их. Т.е. да, сохранение, фактически, ведётся в два этапа. И refresh() тут нужен - иначе проверить сохранённые атрибуты нельзя.

По факту, такую же логику придётся писать всегда, если мы захотим реализовать связь между двумя моделями.

Какие вижу решения:
1. Не использовать createModel в тех моделях, где нет релейшенов. Минус - потеря унификации кода.
2. Забить на оверхед ради унификации. Релейшены, рано или поздно, появляются везде, и выгода перевешивает.
3. Сейчас updateModel() - это алиас к createModel(), а при апдейте рефреш не нужен. Да, если уж на то пошло, то и проверки не нужны - можно просто делать save(), и оно должно работать. Хоба, я решил 80% задачи.
4. ... взгляни на задачу незамутнённым взглядом и предложи своё решение.

**Comment by pozitronik** [comment]
5. А вот решение, которое мне кажется абсолютно правильным: https://github.com/pozitronik/yii2-core-tools/commit/49ea8958b89d356012484f1cf2d0626b4cff4469

**Comment by alxlapin** [comment]
Пока по части оптимизаций выскажусь.

```php

if (null !== $model = static::findOne([self::getFirstAttributeName() => self::extractKeyValue($master), self::getSecondAttributeName() => self::extractKeyValue($slave)])) {
	/** @var ActiveRecord $model */
	$model->delete();
}
```
Может лучше так?:
```php
static::deleteAll([self::getFirstAttributeName() => self::extractKeyValue($master), self::getSecondAttributeName() => self::extractKeyValue($slave)])
```

Аналогично:
```php
foreach (static::findAll([self::getFirstAttributeName() => self::extractKeyValue($master)]) as $model) {
	/** @var ActiveRecord $model */
	$model->delete();
}
```

можно заменить на:
```php
static::deleteAll([self::getFirstAttributeName() => self::extractKeyValue($master)])
```

**Comment by alxlapin** [comment]
Для уточнения: данный трейт предусматривает первоначальное сохранение таблицы релейшенов, и только потом производится сохранение связываемых сущностей, я правильно понимаю?

**Comment by pozitronik** [comment]
> 
> 
> Пока по части оптимизаций выскажусь.
> 
Принимается.

**Comment by pozitronik** [comment]
[Написал доку](https://github.com/pozitronik/yii2-core-tools/wiki/%D0%9A%D0%B0%D0%BA-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D1%81-%D1%82%D1%80%D0%B5%D0%B9%D1%82%D0%BE%D0%BC-Relations)
