### ISSUE TITLE
Не меняется Users::$_current после авторизации под другим пользователем

### ISSUE THREAD

**Issue by artemvolt** [cusodede/bc#44]
https://github.com/cusodede/bc/blob/master/models/sys/users/Users.php 67 строка.
Например, в тестах если авторизоваться сперва под менеджером, то в $_current будет модель менеджера, но если мы дальше авторизуемся под админом, то в $_current ничего не поменяется - будет менеджера.
Как итог - hasPermission в контроллере будет проверять права менеджера.
Как вариант, в методе login сбрасывать свойство.
Этот баг можно увидеть только если в рамках одно запроса сделать несколько раз авторизацию под разными пользователями.

**Comment by pozitronik** [comment]
@artemvolt, чекни на ветке **users-current-opt**.
@alxlapin, похоже всё-таки возьмём твою реализацию. Здесь я уже вынужден отступить, потому что идея, которую я пытался реализовать, уже не перевешивает тех проблем, которые создаются.

**Comment by artemvolt** [comment]
С этим все ок. Можно вливать.
