### ISSUE TITLE
Формат логов для постановки на мониторинг

### ISSUE THREAD

**Issue by pozitronik** [cusodede/bc#50]
Описание: https://confluence.veon.com/pages/viewpage.action?pageId=159664843
Реализация: доработать sys_exceptions, добавив опциональный вывод в файл + добавить методы а-ля Yii::debug() для произвольного протоколирования.

**Comment by alxlapin** [comment]
Возможно, пригодится 

- https://github.com/Seldaek/monolog
- https://github.com/samdark/yii2-psr-log-target

**Comment by alxlapin** [comment]
+ https://github.com/samdark/yii2-psr-log-target
