### ISSUE TITLE
Доступы GraphQL API

### ISSUE THREAD

**Issue by pozitronik** [cusodede/bc#53]
Нужно (или не нужно - см. далее) придумать способ разграничивать доступ к GraphQL-запросам (схема/поле), подобно тому как мы можем разграничивать доступ controller/action.
Зачем: допустим, у пользователя A есть доступ к какому-то фронтовому вью, данные которого получаются запросом `query{method{field{}}`. У пользователя B такого доступа нет.

По идее, клиент фронта сам должен запрашивать у бека права авторизованного пользователя и рисовать/не рисовать ему это вью. В таком случае серверная проверка выступает дополнительной защитой + закрывает кейс, когда кто-то хитроумный попытается сделать поддельный запрос.
Но если кто-то что-то посмотрит - это не сильно плохо. Вот если кто-то что-то мутирует - это уже плохо сильно.

Мысли по поводу:
1. Надо спросить фронтов, как они доступы разруливают. Возможно, достаточно будет модифицировать GQL-схему в зависимости от прав авторизованного юзера.
2. Должны быть GQL-методы, доступные без авторизации (собсно, авторизация) и не доступные без авторизации.
3. Никаких предлагаемых решений в вендорском пакете или известных мне надстройках над ним я не нашёл, похоже действительно подразумевается решение выше.
4. Реализовать изменение схемы достаточно просто: в `QueryType::__construct()` проверять доступы и формировать схему по ним.

Кто что думает ещё?

**Comment by Fullchaos** [comment]
Тут очень важный вопрос, если мы будем отдавать схему, в зависимости от прав пользователя, то могут возникнут проблемы у ребят на фронте, так как я думаю, что именно схема, должна быть едина, а мы уже, непосредственно перед инсертом в базу или при запросе атрибутов, должны проверять права.

**Comment by Fullchaos** [comment]
Мне кажется, проверку прав, нужно делать на уровне моделей.
