### ISSUE TITLE
ControllerTrait::GetActionUrl

### ISSUE THREAD

**Issue by alxlapin** [cusodede/bc#8]
`$controllerId = self::ExtractControllerId(self::class);`

self::class необходимо заменить на static::class для корректной генерации путей до action'ов, определенных в базовом контроллере (DefaultController), но не переопределенных в дочерних контроллерах

**Comment by pozitronik** [comment]
В отнаследованные контроллеры можно просто добавить трейт ControllerTrait.
Но можно и через static.

**Comment by pozitronik** [comment]
fixed in yii2-core-tools
composer update
